#undef  CONFIG_i386
#define CONFIG_PENTIUMI 1
#undef  CONFIG_PENTIUMII
#undef  CONFIG_PENTIUMIII

#define CONFIG_BIOS_APM 1

#undef  CONFIG_MEMTESTS
//#define CONFIG_MEMTESTS 1

#define CONFIG_DRIVERS_CHAR 1
#define CONFIG_DRIVERS_BLOCK 1
#define CONFIG_DRIVERS_NET 1
#define CONFIG_DRIVERS_NET_RTL_8029 1

#define CONFIG_NET_LAYER_1_ETH 1
#undef  CONFIG_NET_LAYER_1_TR
#define CONFIG_NET_LAYER_2_ARP 1
#define CONFIG_NET_LAYER_3_IP 1
